on:
  release:
    types: [published]

jobs:
  documentation:
    name: Documentation
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Build documentation
        run: mkdocs gh-deploy --force
